name: Build

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-ghlint:
    name: Call Lint Github workflows
    uses: azazeal/workflows/.github/workflows/ghlint.yml@master
    permissions:
      pull-requests: write # required in order to annotate a PR with comments
    
  call-gopkg:
    name: Call Build Go package
    uses: azazeal/workflows/.github/workflows/gopkg.yml@master
    with:
      disable-macos-tests: true
      disable-windows-tests: true
